### ISSUE TITLE
Select a random subset of barcodes

### ISSUE THREAD

**Issue by sjackman** [hackseq/2017_project_6#13]

**Comment by baraaorabi** [comment]
Here's a possible pipeline for this:

Sample without replacement |whitelist|/1000 out of the whitelist of barcodes; put them in a set, whitelist_subset.

Put all whitelisted barcodes in a set, whitelist. 

Go through the fastq file. Have populate three dictionaries:
1- raw_barcodes = {barcode : population}, s.t. barcode is in fastq file
2- whitelisted_raw_barcodes= {barcode : population}, s.t. barcode is in whitelist and in fastq file
3- non-whitelisted_barcodes = {barcode: population}, s.t. barcode is not in whitelist but in fastq file

Additionally, as you go through the fastq file, if a read's barcode is in whitelist_subset, print it out.
