### ISSUE TITLE
De novo chromeqc

### ISSUE THREAD

**Issue by emreerhan** [hackseq/2017_project_6#15]
Generate the report de novo without using a reference genome.

    assemble the reads, using perhaps BCALM
    select the largest contigs of the assembly
    determine the barcodes that map to those contigs
    reassemble those barcodes to create a new assembly
    run the above analysis using that assembly as the reference

**Comment by emreerhan** [comment]
The largest contig maps to  Homo sapiens chromosome 5 clone CTC-499J9, complete sequence

**Comment by sjackman** [comment]
We didn't quite get around to this one.
