### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by rchikhi** [hackseq/2017_project_6#16]
Sample report link for ChromeQC appears broken: https://hackseq.github.io/2017_project_6/report/

**Comment by sjackman** [comment]
Woops. I missed this bug report. Thanks, Rayan! The correct links are:
+ [Sample ChromeQC report](http://bcgsc.github.io/chromeqc/report)
+ [Sample MultiQC report](https://bcgsc.github.io/chromeqc/multiqc/)
