### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by sjackman** [hackseq/2017_project_6#3]
👋 Welcome. Let's chat!

**Comment by sjackman** [comment]
@emreerhan @hyounesy @JustinChu @realseanla @tmozgach
Hello! Who's local to Vancouver, and who's participating remotely?

**Comment by emreerhan** [comment]
Hi everyone. I'm a local undergrad at SFU. I'm looking forward to working with all of you 😄

**Comment by sjackman** [comment]
Here's an outline of the pipeline that we'll develop: https://github.com/hackseq/2017_project_6/issues/2

**Comment by tmozgach** [comment]
Hello everyone, I am a grad at SFU.
@sjackman because we all have different background, may be it is good idea to provide some background information about biological concepts (links, papers, tutorials, chapters of book) and technical tutorials that will be useful in your opinion, before Hackseq?

**Comment by sjackman** [comment]
The 10x Genomics web site, their white papers, and their videos, will give you a background on the technology:
https://www.10xgenomics.com/technology/
https://www.10xgenomics.com/genome/
https://www.10xgenomics.com/application-notes/

**Comment by baraaorabi** [comment]
Thnx @sjackman for preparing this repo

I'm an SFU grad student. I believe I'll be able to attend the full schedule starting from Fri afternoon (got class in the morning). Looking forward to meeting y'all!

**Comment by sjackman** [comment]
@hackseq/2017_team_6 Please install [this software](https://github.com/hackseq/2017_project_6/issues/4) on your laptop before Friday!

There's two reasons:

1. 🐢 Downloading software over wifi with 100 other participants can be painfully slow.
2. :running_woman: We can troubleshoot installation issues before Friday so that we can hit the ground running.

**Comment by sean-la** [comment]
Hello! I'm an SFU undergrad too, and I'll be participating remotely on the first day (I've got class and a tutorial I need to teach). Otherwise, I'll be at UBC campus on the weekend.

**Comment by sjackman** [comment]
If you're unfamiliar with Git, there's a Introduction to Git workshop on Thursday night.

On campus at UBC, Vancouver | Room D213, Chemistry building
18:30 - 20:30, October 19th, Thursday

http://www.hackseq.com/schedule

Cloning this repository is a good first exercise if you're new to Git, and also a way to confirm that the Git software is correctly installed on your system. You can use either the command line `git`, the graphical interface [GitHub Desktop](https://desktop.github.com), or one of many other graphical interfaces.

**Comment by rylosqualo** [comment]
Hi, all! I will be joining remotely from San Francisco.

**Comment by sjackman** [comment]
Great to have you, Ryan!

**Comment by sm30** [comment]
Hi All! I'm Swapna from India- joining remotely, opposite time zone.

**Comment by sjackman** [comment]
Hi, Swapna! Happy to have you on board. We're at UTC-08:00 in Vancouver and you're at UTC+05:30 in India, so we're 13.5 hours apart. 9:00 in Vancouver is 22:30 in India. We can overlap by an hour and a half if you stay up until midnight. We'll post a summary of our work on GitHub so that you can keep up with our progress. When we disband for the day at 18:00, which is 7:30 in India, I'll post some open tasks and suggestions of what you might work on.

**Comment by sm30** [comment]
Hi Shaun, great to be working with all of you too. Plan sounds good- I'll be up till midnight and work during the day based on your summary and suggestions. Any tasks on visualization, analyses are welcome. I have intermediate skills with R and comfortable with other bioinfo software, strong suit-biology. Thanks!

**Comment by sjackman** [comment]
You could work on any of these steps of the pipeline (see issue #2).

> Compute molecule and barcode statistics with R (see below)
 Generate the report with RMarkdown notebook or dashboard
 Aggregate multiple reports with MultiQC

The input to that stage is a TSV file with these columns:
```
BX, Rname, Start, End, Reads, possibly Mapq_median, AS_median, NM_median
```
`End - Start` is the size of the molecule, and the number that we're most interested in.

**Comment by sm30** [comment]
Okay..do we have a TSV file or will it be generated by the previous steps?

**Comment by sjackman** [comment]
Not yet, not with real data. You could make some fake data four the purposes of getting a head start.

**Comment by sjackman** [comment]
Great working with you all!
