### ISSUE TITLE
Install software on participants' laptops

### ISSUE THREAD

**Issue by sjackman** [hackseq/2017_project_6#4]
Please install the following software on your laptop:

# macOS

1. [Homebrew](https://brew.sh)
2. RStudio `brew cask install r rstudio`
3. IGV `brew cask install igv`

# Linux

1. [Linuxbrew](http://linuxbrew.sh)
2. R `sudo apt-get install r-base` or `brew install homebrew/science/r`
3. [RStudio](https://www.rstudio.com/products/rstudio/download/#download)
4. IGV `brew install homebrew/science/igv`

# Windows (all versions)

1. [R](https://cran.r-project.org/bin/windows/base/)
2. [RStudio](https://www.rstudio.com/products/rstudio/download/#download)
3. [Github Desktop](https://desktop.github.com)
4. [IGV](https://software.broadinstitute.org/software/igv/download)

# Windows 10

1. [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)
2. [Linuxbrew](http://linuxbrew.sh)

# Windows < 10

1. [Docker for Windows](https://www.docker.com/docker-windows)
2. [Git for Windows](https://git-scm.com/download/win)

**Comment by hyounesy** [comment]
Are there any:
- specific R packages to install?
- large data files (fastq, bam) to download?

**Comment by sjackman** [comment]
R packages: `tidyverse` and `rmarkdown`

Large data files: hopefully you won't need the large data files on your laptop. We'll be using the [BCGSC ORCA](http://www.bcgsc.ca/services/orca) machines for the big data computation. We'll then copy smaller tab-separated-values (TSV) files to our laptops for analysis in R.

If you wanted to download the raw sequencing data for fun, there's three data sets here:
https://github.com/hackseq/2017_project_6/blob/master/Makefile#L65-L78

**Comment by sjackman** [comment]
The complete BAM file for one of these individuals is here, but it's 106 GB. We'll be using a subset of it:
ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/10XGenomics_ChromiumGenome_LongRanger2.1_09302016/NA24143_GRCh38/NA24143_GRCh38_phased_possorted_bam.bam

**Comment by JustinChu** [comment]
Subsetting chromium data is tricky. If we randomly subset, we will dilute the already low sub 1x molecule coverage, and if we subset by aligning (to chr21, for example), we will unfairly make the multi-index problem much less of an issue (it will look like each BX tag is unique to a molecule).

I wonder if we could find a smaller 10x dataset?

Perhaps we should explore simulating data with [LRSIM](https://github.com/aquaskyline/LRSIM)?

**Comment by sjackman** [comment]
The plan is to use a single lane of data, which is roughly 2 fold read depth of coverage of the genome.
Our tool will further subsample by barcode, decimating the barcodes by say 1/1000.
