### ISSUE TITLE
Estimate molecule size using alignment

### ISSUE THREAD

**Issue by JustinChu** [hackseq/2017_project_6#6]
Python script that accepts a bam file to estimate molecule size.
- [x]  Add Parsing options for AS and NM
- [ ]  Add some IGV figures showing molecules using IGV 2gb BAM file and TSV and actual bam file

**Comment by JustinChu** [comment]
Columns: BX, MI, RefName, Start, End, Reads
Optional Columns: interarrival_stdev, Mapq_median, AS_median, NM_median
An output example:
```
ATATACGTACTACGTTACGTTACGTA	0	chr1	129	1023	53	22
```

**Comment by sjackman** [comment]
Let's put the columns in the same order as a BED file so that it's easy to convert to BED with `cut -f1-5`
1. Rname
2. Start
3. End
4. BX
5. Reads
6. MI
