### ISSUE TITLE
Generate final Rmarkdown report 

### ISSUE THREAD

**Issue by cheny19** [hackseq/2017_project_6#8]
I'll first work on a rmarkdown template that includes potential figures and statistics we want to report. And when different components of the pipeline are done, I'll glue them together and generate the final report.

**Comment by sjackman** [comment]
Swapna (@sm30) is also working on this task.
@cheny19 Can you work on aggregating reports with MultiQC?

**Comment by sjackman** [comment]
Here's inspiration for the report:
Loupe: https://github.com/hackseq/2017_project_6/blob/master/hg002g1_lrwgsvc/outs/summary.png
FastQC: https://www.bioinformatics.babraham.ac.uk/projects/fastqc/

**Comment by sjackman** [comment]
The input of this step may look something like this data from Longranger wgs:
https://github.com/hackseq/2017_project_6/blob/master/hg002g1_lrwgsvc/outs/summary.csv
