### ISSUE TITLE
Compute molecule and barcode statistics with R

### ISSUE THREAD

**Issue by sjackman** [hackseq/2017_project_6#9]
The output of this step may look something like this output generated by Longranger wgs:
https://github.com/hackseq/2017_project_6/blob/master/hg002g1_lrwgsvc/outs/summary.csv

**Comment by tmozgach** [comment]
Input: BX, MI, RefName, Start, End, Length_stdev, Reads
AAAA GGGG TTTT CCCC 0 chr127 153 500 2 28

Output: 
GEM detected (number of unique barcodes (BX))
Linked-Reads per Molecule (mean of Reads (field))
Molecule length (End - Start)

Plot:
ggplot2 
Weight = length

**Comment by tmozgach** [comment]
@sjackman @JustinChu  Guys, could you write down more things to try and you want to see?

**Comment by sjackman** [comment]
Take a look at this screenshot from Loupe:
https://github.com/hackseq/2017_project_6/blob/master/hg002g1_lrwgsvc/outs/summary.png

**Comment by sjackman** [comment]
N50 Linked reads per molecule (LPM)
You'll need a function that calculates the N50 of a vector of integers. You can likely find one online if you Google for it.

**Comment by sjackman** [comment]
Plots of…
- Molecule size
- Total DNA per barcode
- Molecules per barcode
- Reads per molecule
- Reads per barcode
